"use client";

import { useState, useEffect, useCallback } from "react";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import { Button } from "@/components/ui/button";
import {
  AlertTriangle,
  ChevronDown,
  Info,
  OctagonAlert,
  X,
} from "lucide-react";
import { toast } from "sonner";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface Annotation {
  id: string;
  sectionHeading: string;
  concern: string;
  severity: "info" | "warning" | "error";
  createdAt: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Slugify a heading to match the IDs generated by article-content.tsx.
 * Must stay in sync with the slugify function in table-of-contents.tsx.
 */
function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * Format a timestamp as a relative time string (e.g. "2 hours ago").
 */
function formatRelativeTime(dateStr: string): string {
  const now = Date.now();
  const then = new Date(dateStr).getTime();
  const diffMs = now - then;
  const diffSec = Math.floor(diffMs / 1000);
  const diffMin = Math.floor(diffSec / 60);
  const diffHour = Math.floor(diffMin / 60);
  const diffDay = Math.floor(diffHour / 24);

  if (diffDay > 0) return `${diffDay}d ago`;
  if (diffHour > 0) return `${diffHour}h ago`;
  if (diffMin > 0) return `${diffMin}m ago`;
  return "just now";
}

const HIGHLIGHT_CLASS = "annotation-highlight";

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * Collapsible banner showing AI review annotations for an article.
 *
 * - Fetches active annotations on mount
 * - Renders nothing if no annotations exist
 * - Each annotation card shows severity icon, section link, concern, timestamp, and dismiss button
 * - Clicking a section heading scrolls to that heading in the article
 * - Adds yellow left-border highlight to referenced section headings
 * - Dismissing removes the annotation from UI and marks it dismissed in the database
 */
export function AnnotationBanner({
  articleId,
  initialCount,
}: {
  articleId: string;
  initialCount?: number;
}) {
  const [annotations, setAnnotations] = useState<Annotation[]>([]);
  const [isOpen, setIsOpen] = useState(false);
  const [loading, setLoading] = useState(true);

  // Fetch annotations on mount
  useEffect(() => {
    let cancelled = false;

    async function fetchAnnotations() {
      try {
        const res = await fetch(`/api/articles/${articleId}/annotations`);
        if (!res.ok) return;
        const data: Annotation[] = await res.json();
        if (!cancelled) {
          setAnnotations(data);
        }
      } catch {
        // Silently fail -- annotations are non-critical
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    fetchAnnotations();
    return () => {
      cancelled = true;
    };
  }, [articleId]);

  // Apply / remove yellow left-border highlights on referenced section headings
  useEffect(() => {
    const highlightedElements: HTMLElement[] = [];

    for (const annotation of annotations) {
      const slug = slugify(annotation.sectionHeading);
      const el = document.getElementById(slug);
      if (el) {
        el.classList.add(HIGHLIGHT_CLASS);
        highlightedElements.push(el);
      }
    }

    return () => {
      for (const el of highlightedElements) {
        el.classList.remove(HIGHLIGHT_CLASS);
      }
    };
  }, [annotations]);

  // Scroll to a section heading when clicking an annotation
  const scrollToSection = useCallback((sectionHeading: string) => {
    const slug = slugify(sectionHeading);
    const el = document.getElementById(slug);
    if (el) {
      el.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  }, []);

  // Dismiss an annotation
  const dismissAnnotation = useCallback(
    async (annotationId: string) => {
      // Optimistic removal
      setAnnotations((prev) => prev.filter((a) => a.id !== annotationId));

      try {
        const res = await fetch(
          `/api/articles/${articleId}/annotations/${annotationId}/dismiss`,
          { method: "POST" }
        );
        if (!res.ok) {
          throw new Error("Failed to dismiss");
        }
        toast.success("Annotation dismissed");
      } catch {
        // Revert: re-fetch annotations
        try {
          const res = await fetch(`/api/articles/${articleId}/annotations`);
          if (res.ok) {
            const data: Annotation[] = await res.json();
            setAnnotations(data);
          }
        } catch {
          // Ignore
        }
        toast.error("Failed to dismiss annotation");
      }
    },
    [articleId]
  );

  // Don't render anything if there are no annotations
  // Show the header bar immediately if we have an initialCount > 0
  if (!loading && annotations.length === 0 && !initialCount) {
    return null;
  }
  if (loading && !initialCount) {
    return null;
  }

  const count = annotations.length || initialCount || 0;
  if (count === 0 && !loading) {
    return null;
  }

  return (
    <>
      {/* Inline styles for section highlighting */}
      <style>{`
        .${HIGHLIGHT_CLASS} {
          border-left: 3px solid oklch(0.828 0.189 84.429);
          padding-left: 0.5rem;
        }
      `}</style>

      <Collapsible open={isOpen} onOpenChange={setIsOpen}>
        <CollapsibleTrigger asChild>
          <button
            type="button"
            className="mb-4 flex w-full items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-left text-sm font-medium text-amber-800 transition-colors hover:bg-amber-100 dark:border-amber-800 dark:bg-amber-950 dark:text-amber-200 dark:hover:bg-amber-900"
          >
            <AlertTriangle className="size-4 shrink-0" />
            <span className="flex-1">
              AI Review: {count} item{count !== 1 ? "s" : ""} need
              {count === 1 ? "s" : ""} attention
            </span>
            <ChevronDown
              className={`size-4 shrink-0 transition-transform ${isOpen ? "rotate-180" : ""}`}
            />
          </button>
        </CollapsibleTrigger>

        <CollapsibleContent>
          <div className="mb-4 space-y-2">
            {annotations.map((annotation) => (
              <AnnotationCard
                key={annotation.id}
                annotation={annotation}
                onScrollToSection={scrollToSection}
                onDismiss={dismissAnnotation}
              />
            ))}
          </div>
        </CollapsibleContent>
      </Collapsible>
    </>
  );
}

// ---------------------------------------------------------------------------
// Annotation Card
// ---------------------------------------------------------------------------

function AnnotationCard({
  annotation,
  onScrollToSection,
  onDismiss,
}: {
  annotation: Annotation;
  onScrollToSection: (sectionHeading: string) => void;
  onDismiss: (id: string) => void;
}) {
  return (
    <div className="flex items-start gap-3 rounded-md border border-border bg-card p-3 text-sm">
      <SeverityIcon severity={annotation.severity} />

      <div className="min-w-0 flex-1">
        <button
          type="button"
          onClick={() => onScrollToSection(annotation.sectionHeading)}
          className="mb-1 font-medium text-primary underline-offset-2 hover:underline"
        >
          {annotation.sectionHeading}
        </button>
        <p className="text-muted-foreground">{annotation.concern}</p>
        <span className="mt-1 block text-xs text-muted-foreground/70">
          {formatRelativeTime(annotation.createdAt)}
        </span>
      </div>

      <Button
        variant="ghost"
        size="icon"
        className="size-7 shrink-0"
        onClick={() => onDismiss(annotation.id)}
        aria-label="Dismiss annotation"
      >
        <X className="size-3.5" />
      </Button>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Severity Icon
// ---------------------------------------------------------------------------

function SeverityIcon({
  severity,
}: {
  severity: "info" | "warning" | "error";
}) {
  switch (severity) {
    case "info":
      return <Info className="mt-0.5 size-4 shrink-0 text-blue-500" />;
    case "warning":
      return (
        <AlertTriangle className="mt-0.5 size-4 shrink-0 text-amber-500" />
      );
    case "error":
      return (
        <OctagonAlert className="mt-0.5 size-4 shrink-0 text-red-500" />
      );
  }
}
